DataCollectingSite/urls.py
# from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('download/', include('download.urls')),
    path('home/', views.home, name='home'),
    path('synchronize/', views.synchronize, name='synchronize'),
    path('upload/', include('upload.urls')),
    # path('admin/', admin.site.urls),
]

download/urls.py
from django.urls import path

from . import views


app_name = 'download'
urlpatterns = [
    path('', views.show_list, name='project_list'),
    path('search', views.search, name='search'),
    path('<project_name>', views.show_detail),
    path('<project_name>/<type>', views.show_more_detail, name='detail'),
    path('file/<project_name>', views.download, name='file'),

]

upload/urls.py
from django.urls import path

from . import views


app_name = 'upload'
urlpatterns = [
    path('', views.home, name='home'),
    path('file', views.upload_file),
]

download/models.py
from django.db import models
import datetime

# Create your models here.
from django.utils import timezone


# class Question(models.Model):
#     question_text = models.CharField(max_length=200)
#     pub_date = models.DateTimeField('date published')
#
#     def __str__(self):
#         return self.question_text
#
#     def was_published_recently(self):
#         return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
#
#
# class Choice(models.Model):
#     question = models.ForeignKey(Question, on_delete=models.CASCADE)
#     choice_text = models.CharField(max_length=200)
#     votes = models.IntegerField(default=0)
#
#     def __str__(self):
#         return self.choice_text


class ProjectInfo(models.Model):
    name = models.CharField(max_length=128)
    source = models.CharField(max_length=32)
    path = models.FilePathField(path="E:/Apache", allow_folders=True, recursive=True, max_length=256)
    files_cnt = models.IntegerField(default=0)
    size = models.IntegerField(default=0)
    preview_path = models.FilePathField(path="E:/Apache", recursive=True, null=True, max_length=256)

DataCollectingSite/views.py
from django.template import loader
from django.http import HttpResponse, JsonResponse
from download.syn_db import SynDB


def home(request):
    template = loader.get_template('home.html')
    context = {
    }
    return HttpResponse(template.render(context, request))


def synchronize(request):
    SynDB.syn_db()
    return JsonResponse({'status': 'success'})

download/views.py
# Create your views here.

from django.http import HttpResponse, HttpResponseRedirect, FileResponse
from django.shortcuts import render
from django.db.models import Count, Sum
from .models import ProjectInfo
from django.urls import reverse
import os
import zipfile


def create_zip(path_list, save_path, project_name):
    tar_name = project_name
    for pro in path_list:
        tar_name = tar_name + '_' + pro['type']
    tar_name = tar_name + '.zip'
    new_zip = zipfile.ZipFile(save_path + tar_name, 'w')

    for pro in path_list:
        for dir_path, dir_names, file_names in os.walk(pro['path']):
            for file_name in file_names:
                file_path = os.path.join(dir_path, file_name)
                new_zip.write(file_path, project_name + '/' + pro['type'] + '/' + file_path[len(pro['path']):])

    new_zip.close()
    return tar_name


def show_list(request):
    projects = ProjectInfo.objects.values('name').annotate(count=Count('id'), size=Sum('size')).order_by('name')
    context = {'project_list': projects}
    return render(request, 'project_list.html', context)


def show_more_detail(request, project_name, type):
    items = ProjectInfo.objects.filter(name=project_name)
    types = []
    project_info = ProjectInfo()
    for item in items:
        if item.source == type:
            types.append({'name': item.source, 'active': True})
            project_info = item
        else:
            types.append({'name': item.source, 'active': False})
    context = dict()
    context['project_name'] = project_name
    context['item'] = project_info
    context['types'] = types
    if project_info.source == 'CODE':
        context['code'] = "unsupported"
    else:
        context['code'] = open(project_info.preview_path, 'r+').read(4096)
    return render(request, 'project_detail.html', context)


def show_detail(request, project_name):
    items = ProjectInfo.objects.filter(name=project_name)
    return HttpResponseRedirect(reverse('download:detail', args=(project_name, items[0].source)))


def download(request, project_name):
    types = request.POST.getlist('types')
    path_list = []
    for type in types:
        item = ProjectInfo.objects.get(name=project_name, source=type)
        path_list.append({'path': item.path, 'type': type})
    tar_name = create_zip(path_list, 'E:/', project_name)
    response = FileResponse(open('E:/' + tar_name, 'rb'), content_type="application/zip")
    response['Content-Disposition'] = 'attachment; filename="' + tar_name + '"'
    return response


def search(request):
    str = request.GET.get('str')
    projects = ProjectInfo.objects.values('name').annotate(count=Count('id'), size=Sum('size')).filter(name__contains=str).order_by('name')
    context = {'project_list': projects}
    return render(request, 'project_list.html', context)

upload/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
# Create your views here.


def home(request):
    return render(request, 'upload_home.html')


def handle_uploaded_file(f):
    with open('E:/upload/' + f.name, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


def upload_file(request):
    if request.method == 'POST':
        f = request.FILES['myfile']
        handle_uploaded_file(f)
        return HttpResponse("success")

    return HttpResponse("fail")

download/templates/project_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Detail-{{ project_name }}</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body style="padding-top: 50px">

<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">

        <div class="navbar-header">
            <span class="navbar-brand">Software Collecting Site</span>
        </div>

    </div>
</nav>




<div class="container">
    <br />
    <a href="{% url 'download:project_list' %}">back</a>

    <div class="page-header">
        <h1 id="name">{{ project_name }}</h1>
    </div>

    <div>
        <form action="{% url 'download:file' project_name %}" method="post">
        {% csrf_token %}
            <input class="btn btn-primary btn-lg" type="submit" value="Download" >
            <br /> <br />
            {% for type in types %}
                <p> <input type="checkbox" name="types" value="{{ type.name }}" >  {{ type.name }} </p>
            {% endfor %}
            <br />
        </form>
    </div>

    <ul class="nav nav-tabs">
        {% for type in types %}
            {% if type.active %}
            <li class="active"><a>{{ type.name }}</a></li>
            {% else %}
            <li><a href= "{% url 'download:detail' project_name type.name %}" >{{ type.name }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>

    <div class="panel panel-default">
        <div class="panel-body">
            <p>number of files: {{ item.files_cnt }}</p>
            <p>size: {{ item.size }}MB</p>
            <br />
            <p>Preview</p>
            <pre>{{ code }}</pre>

        </div>
    </div>


</div>



<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/vue/2.4.2/vue.min.js"></script>



</body>
</html>

download/templates/project_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Project List</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body style="padding-top: 50px">

<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">

        <div class="navbar-header">
            <span class="navbar-brand">Software Collecting Site</span>
        </div>

        <div class="navbar-form navbar-right">
            <form action="{% url 'download:search' %}" method="get">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search" name="str">
                </div>
                <input class="btn btn-default" type="submit" value="Submit">
            </form>


        </div>

    </div>
</nav>




<div class="container">

    <div class="page-header">
        <h3>Project List</h3>
    </div>



    <table class="table table-striped">
        <colgroup>
            <col width="70px">
        </colgroup>
        <thead>
            <tr>
                <th>#</th>
                <th>Project name</th>
                <th>Source</th>
                <th>Size</th>
            </tr>
        </thead>
        <tbody>
        {% if project_list %}
            {% for project in project_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ project.name }}">{{ project.name }}</a></td>
                <td>{{ project.count }} source(s)</td>
                <td>{{ project.size }}MB</td>
            </tr>
            {% endfor %}
        {% endif %}

        </tbody>
    </table>

    <nav>
        <ul class="pagination">
            <li>
                <a href="#" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
            <li class="active">
                <span>1</span>
            </li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><a href="#">5</a></li>
            <li>
                <a href="#" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>



</div>



<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/vue/2.4.2/vue.min.js"></script>


</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>home</title>
</head>
<body>
<p>
<a href="{% url 'download:project_list' %}">Show Project List</a>
</p>
<p>
<a href="{% url 'upload:home' %}">Upload File</a>
</p>
<button onclick="synchronize()">Synchronize Database Information</button>
<p style="display: none" id="alert"></p>

</body>
</html>
<script>
    function synchronize() {
        var alert = document.getElementById('alert');

        alert.textContent='synchronizing';
        alert.style.display='block';

        $.ajax({
            type: "Get",
            url: "{% url 'synchronize' %}",
            async: false,
            data: {},
            success: function (data) {
                if (data.status === 'success') {
                    alert.textContent='database synchronized';
                }

            }
        });
    }
</script>

<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>

upload/templates/upload_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <title>Project List</title>

    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

</head>

<body style="padding-top: 50px">

<nav class="navbar navbar-default navbar-fixed-top">

    <div class="container">

        <div class="navbar-header">
            <span class="navbar-brand">Software Collecting Site</span>
        </div>


    </div>
</nav>




<div class="container">

    <div class="page-header">
        <h3>Upload files</h3>
    </div>

    <form enctype="multipart/form-data" method="post" action="file">
        {% csrf_token %}
        <input type="file" id="fileToUpload" name="myfile" onchange="fileSelected()"/>
        <br />
        <button type="submit" class="btn btn-default">Submit</button>
    </form>

    <br />

    <p id="fileName"></p>
    <p id="fileSize"></p>
    <p id="fileType"></p>





</div>



<!-- Bootstrap core JavaScript
================================================== -->

<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="https://cdn.bootcss.com/vue/2.4.2/vue.min.js"></script>
<script>
    function fileSelected() {
        var file = document.getElementById('fileToUpload').files[0];
        if (file) {
            var fileSize = 0;
            if (file.size > 1024 * 1024){
                fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
            }else{
                fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';
            }

            document.getElementById('fileName').innerHTML = 'Name: ' + file.name;
            document.getElementById('fileSize').innerHTML = 'Size: ' + fileSize;
            document.getElementById('fileType').innerHTML = 'Type: ' + file.type;
        }
    }
</script>

</body>
</html>